[package]
name = "ibank-wallet-chains"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
rlp = "0.5"
sha3 = "0.10"
hex = "0.4"
ibank-wallet-core = { path = "../ibank-wallet-core" }
